name: Python Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10  # Specify the Python version you want to use

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install coverage  # Install the coverage package

    # Step 4: Run tests with coverage
    - name: Run tests and measure coverage
      run: |
        coverage run -m unittest discover -s . -p "test_*.py"

    # Step 5: Report coverage
    - name: Generate coverage report
      run: |
        coverage report
        coverage html  # Optional: Generate an HTML report for coverage

    # Step 6: Upload coverage report as an artifact (optional)
    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: htmlcov  # The directory where the HTML report is generated
