name: Python Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10  # Specify the Python version you want to use

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install coverage snakeviz  # Install coverage and profiling tools

    # Step 4: Run tests with coverage
    - name: Run tests and measure coverage
      run: |
        coverage run -m unittest discover -s . -p "test_*.py"

    # Step 5: Generate coverage report
    - name: Generate coverage report
      run: |
        coverage report
        coverage html

    # Step 6: Profile tests
    - name: Profile tests
      run: |
        python -m cProfile -o profile_output.prof -m unittest discover -s . -p "test_*.py"

    # Step 7: Convert profiling data to readable format
    - name: Generate profiling report
      run: |
        python -c "import pstats; p = pstats.Stats('profile_output.prof'); p.strip_dirs().sort_stats('cumulative').print_stats(50)" > profiling_report.txt

    # Step 8: Upload coverage and profiling reports
    - name: Upload reports
      uses: actions/upload-artifact@v3
      with:
        name: reports
        path: |
          htmlcov  # HTML coverage report
          profiling_report.txt  # Text-based profiling report
